# kairo.dev

title: Kairo de Araujo
#email: your-email@example.com
description: >-
  I am an Engineer with over two decades in IT.
  I contribute to open source.

  I hail from Brazil and live in The Netherlands.
  I'm a father, husband, and vinyl collector.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kairo.dev" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kairoaraujo
github_username:  kairoaraujo
linkedin_username: kairoaraujo

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
